added license headers
ChainSafeSystems/fixed-sized-numbers-ts pull request #8
Opened 2018-12-27 20:10 UTC by ChainSafe

2018-12-27 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ChainSafeSystems/fixed-sized-numbers-ts?pullRequest=8) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ChainSafeSystems/fixed-sized-numbers-ts?pullRequest=8) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ChainSafeSystems/fixed-sized-numbers-ts?pullRequest=8) it.</sub>

2018-12-27 20:15 UTC, ChainSafe commented
#7

2018-12-28 11:20 UTC, ansermino requested changes
Please lint headers.

2019-01-03 13:46 UTC, GregTheGreek commented
@ChainSafe

2019-01-07 21:31 UTC, ansermino commented
@ChainSafe this should be apache as well

2019-02-21 15:35 UTC, closed without merging